### ISSUE TITLE
leg blaze pet hpb bug

### ISSUE THREAD

**Issue by rhthfhwiejt** [SkyCryptWebsite/SkyCrypt#1431]
**Describe the bug**
legendary blaze pet shows the double potato book effect on armour, but not on weapons.

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/giftMVP/Blueberry)

additional info
frozen blaze armour and legendary blaze pet

**Expected behavior**
for it to show on weapons, as it does in game

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]

**Smartphone (please complete the following information):**

I am on Android and was using the app when I found the bug

**Additional context**

**Comment by dukio** [comment]
Yeah this is how we get the data from hypixel, my theory is since the profile saves when you swap server or disconnect, in those moments you are not really holding anything in hand, so there's nothing to double hpb on...

Either way thanks for reporting this, but fixing this manually would require a lot of time for a very little benefit so it will most likely remain how it is right now
