### ISSUE TITLE
Scrollbars on mobile view being cut off by inventory

### ISSUE THREAD

**Issue by lochyj** [SkyCryptWebsite/SkyCrypt#606]
**Describe the bug**

**Profile/Location**
[My profile](https://sky.shiiyu.moe/stats/lochyj/Lime#Inventory)

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**
The scrollbar needs to have a larger margin as to not have it cut off by the inventory, not get cut off by the inventory

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/79903111/125702752-95bc3306-f9be-4b3a-adb6-a2d21d48bb65.JPG)

**Desktop:**

- OS: Windows 10
- Browser: Chrome, at 700px and under
- Version: 91

**Additional context**
None

**Comment by nstringham** [comment]
This affects a small number of users because more devices with a screen narrower than 700px do not have mice

I would consider this a low priority bug

I plan to refactor the tabs someday and when I do, I will make sure I fix this

**Comment by lochyj** [comment]
Thanks, i do actually mean the bar that indicates how far across the tabs you are as show in the photo, i would fix this myself but i hate databases and can't be bothered to setup the environment on my laptop.

Thanks

**Comment by nstringham** [comment]
> Thanks, i do actually mean the bar that indicates how far across the tabs you are as show in the photo, i would fix this myself but i hate databases and can't be bothered to setup the environment on my laptop.
> 
> Thanks

Yes I realize you're referring to the horizontal scroll bar. The reason that this won't affect very many users is because scroll bars are hidden on mobile and most people who have screens less than 700px wide are mobile users.

If you want to develop the HTML and CSS to solve the problem I would be more than happy to integrate it into the project for you.

The development environment is actually pretty easy to set up if you use the Atlas cloud for a database. Just follow the instructions in https://github.com/SkyCryptWebsite/SkyCrypt/blob/master/CONTRIBUTING.md

**Comment by lochyj** [comment]
OK thanks

**Comment by DuckySoLucky** [comment]
@metalcupcake5
